# World Happiness Report

In [1]:
import pandas as pd

In [22]:
data1=pd.read_csv('Downloads/Happiness World Report 2015-2019/2015.csv')
data2=pd.read_csv('Downloads/Happiness World Report 2015-2019/2016.csv')
data3=pd.read_csv('Downloads/Happiness World Report 2015-2019/2017.csv')
data4=pd.read_csv('Downloads/Happiness World Report 2015-2019/2018.csv')
data5=pd.read_csv('Downloads/Happiness World Report 2015-2019/2019.csv')


df = pd.concat(map(pd.read_csv, ['Downloads/Happiness World Report 2015-2019/2015.csv', 
                                'Downloads/Happiness World Report 2015-2019/2016.csv',
                                 'Downloads/Happiness World Report 2015-2019/2017.csv',
                                 'Downloads/Happiness World Report 2015-2019/2018.csv',
                                 'Downloads/Happiness World Report 2015-2019/2019.csv']))
#df.info()
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [11]:
data1.shape
data2.shape
data3.shape
data4.shape
data5.shape

(156, 9)

In [21]:
pd.merge(data1, data2, how='outer')

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Lower Confidence Interval,Upper Confidence Interval
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,Benin,Sub-Saharan Africa,153,3.484,NaN,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812,3.404,3.564
311,Afghanistan,Southern Asia,154,3.360,NaN,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558,3.288,3.432
312,Togo,Sub-Saharan Africa,155,3.303,NaN,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540,3.192,3.414
313,Syria,Middle East and Northern Africa,156,3.069,NaN,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789,2.936,3.202
314,Burundi,Sub-Saharan Africa,157,2.905,NaN,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404,2.732,3.078